import {User} from "../models/userSchema.js"
import { catchAsyncErrors } from "./catchAsyncErrors.js"
import ErrorHandler from "./error.js"
import jwt from "jsonwebtoken";

export const isAuthenticated=catchAsyncErrors (async(req,res,next)=>{
    // console.log(req);
    console.log(req.cookies);
    // lets check this
    const  token  = req.cookies.token;
    console.log(token);
    if(!token){
        return next(new ErrorHandler("User not Authenticated",400));
    }

    // This verifies that the token is generated by the same secret key 
    const decoded = jwt.verify(token,process.env.JWT_SECRET_KEY);

    // decoded.id---> see userSchema method of generateJsonWebToken
    req.user=await User.findById(decoded.id);

    next();
})